In [1]:
import pandas as pd

In [2]:
from datasets import load_dataset

ds = load_dataset("Mykes/rus_med_dialogues")

/home/alexseyka/.venvs/ml/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df_tr = ds["train"].to_pandas()
df_ts = ds["test"].to_pandas()

In [4]:
df_tr

,topic,user_question,assistant_answer,to_doctor,__index_level_0__,prompt
0,кардиология,У меня учащенное сердцебиение после физической...,Учащенное сердцебиение после физической нагруз...,кардиолог,804,<s><|user|>У меня учащенное сердцебиение после...
1,терапия,"Я принимаю антибиотик Амоксициллин уже 5 дней,...","Понимаю, что кашель не проходит, несмотря на п...",терапевт,501,<s><|user|>Я принимаю антибиотик Амоксициллин ...
2,эндокринология,"У меня постоянно скачет давление. Врач сказал,...",По скачкам давления у Вас может быть действите...,эндокринолог,1448,<s><|user|>У меня постоянно скачет давление. В...
3,травматология,У меня вот уже неделю болит колено после паден...,"Из-за боли в колене после падения, я рекоменду...",травматолог,725,<s><|user|>У меня вот уже неделю болит колено ...
4,онкология,"У меня обнаружили атипию клеток в мазке, что э...",Атипия клеток в мазке может быть признаком раз...,онколог,781,<s><|user|>У меня обнаружили атипию клеток в м...
...,...,...,...,...,...,...
3009,травматология,"У меня растяжение связки лодыжки, что делать?",Растяжение связки лодыжки - это довольно распр...,травматолог,2064,"<s><|user|>У меня растяжение связки лодыжки, ч..."
3010,урология,"У меня болит живот справа, иногда тянущие боли...",Боль в животе справа может быть вызвана разным...,уролог,2670,"<s><|user|>У меня болит живот справа, иногда т..."
3011,психиатрия,"У меня тревога, которая мешает мне спать и сос...","Я понимаю, что Вы беспокоитесь о приеме антиде...",психиатр,3049,"<s><|user|>У меня тревога, которая мешает мне ..."
3012,нутрициология,"У меня проблемы с пищеварением, я часто чувств...","Попробуйте вести пищевой дневник, чтобы отслеж...",гастроэнтеролог,634,"<s><|user|>У меня проблемы с пищеварением, я ч..."
3013,офтальмология,"У меня болит правая глаз, слезясь и щиплет. Чт...","Боли в глазу, слезотечение и ощущение жжения м...",офтальмолог,1982,"<s><|user|>У меня болит правая глаз, слезясь и..."

In [14]:
df_tr = df_tr[["user_question", "assistant_answer"]]
df_ts = df_ts[["user_question", "assistant_answer"]]

In [18]:
df_ts

,user_question,assistant_answer
0,У меня проблемы с пищеварением. Я часто чувств...,"Понимаю, что пищеварение - это очень важная ча..."
1,Я чувствую себя постоянно усталым и подавленны...,Усталость и подавленность - это действительно ...
2,"У меня на руке появилась сыпь, которая чешется...",Сыпь на руке может быть вызвана множеством при...
3,У меня проблемы с эрекцией. Что это может быть?,Проблемы с эрекцией могут иметь различные прич...
4,У меня проблемы с эрекцией. Может ли это быть...,Проблемы с эрекцией могут иметь множество прич...
...,...,...
330,"У меня постоянная головная боль, особенно по у...",Головная боль по утрам и постоянная усталость ...
331,"Подскажите, какие продукты питания полезно упо...","Астма - это серьезное заболевание, которое мож..."
332,У меня снизился либидо и появилась эректильная...,Поскольку у Вас появились проблемы с либидо и ...
333,У меня сильно болит локоть после падения с вел...,"Извините, но я не могу давать медицинские сове..."
334,"У меня мутность в глазах, особенно вечером. Чт...","Мутность в глазах, особенно вечером, может быт..."